#ifndef CONFIG_H
#define CONFIG_H

#define CLIENT_MAX_BODY_LENGTH 1048576
#define CLIENT_MAX_HEADERS_LENGTH 8192
#define CLIENT_MAX_URI_LENGTH 8192

// TODO: adapt for arbitrary methods
#define CLIENT_BUFFER_SIZE (17 + CLIENT_MAX_HEADERS_LENGTH + CLIENT_MAX_URI_LENGTH)

#endif
